defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      # Setup access to our private npm organization
      - run:
          name: Set private npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
